# Generated by Django 4.2.27 on 2026-02-01 12:03

import businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=32)),
                ('year_started', models.PositiveIntegerField()),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('daerah', models.CharField(choices=[('johor_bahru', 'Johor Bahru'), ('muar', 'Muar'), ('batupahat', 'Batu Pahat'), ('alor_setar', 'Alor Setar'), ('sungai_petani', 'Sungai Petani'), ('kota_bharu', 'Kota Bharu'), ('melaka_tengah', 'Melaka Tengah'), ('seremban', 'Seremban'), ('port_dickson', 'Port Dickson'), ('kuantan', 'Kuantan'), ('temerloh', 'Temerloh'), ('ipoh', 'Ipoh'), ('taiping', 'Taiping'), ('kangar', 'Kangar'), ('george_town', 'George Town'), ('seberang_perai', 'Seberang Perai'), ('kota_kinabalu', 'Kota Kinabalu'), ('sandakan', 'Sandakan'), ('tawau', 'Tawau'), ('kuching', 'Kuching'), ('miri', 'Miri'), ('sibu', 'Sibu'), ('petaling', 'Petaling'), ('klang', 'Klang'), ('shah_alam', 'Shah Alam'), ('kuala_terengganu', 'Kuala Terengganu'), ('kuala_lumpur', 'Kuala Lumpur'), ('labuan', 'Labuan'), ('putrajaya', 'Putrajaya'), ('other', 'Lain-lain')], max_length=64)),
                ('postcode', models.CharField(max_length=16)),
                ('negeri', models.CharField(choices=[('johor', 'Johor'), ('kedah', 'Kedah'), ('kelantan', 'Kelantan'), ('melaka', 'Melaka'), ('negeri_sembilan', 'Negeri Sembilan'), ('pahang', 'Pahang'), ('perak', 'Perak'), ('perlis', 'Perlis'), ('pulau_pinang', 'Pulau Pinang'), ('sabah', 'Sabah'), ('sarawak', 'Sarawak'), ('selangor', 'Selangor'), ('terengganu', 'Terengganu'), ('wp_kuala_lumpur', 'W.P. Kuala Lumpur'), ('wp_labuan', 'W.P. Labuan'), ('wp_putrajaya', 'W.P. Putrajaya')], max_length=64)),
                ('ssm_certificate', models.FileField(help_text='PDF upload', max_length=500, upload_to=businesses.models.ssm_certificate_upload_path)),
                ('company_logo', models.ImageField(help_text='JPG/PNG image', max_length=500, upload_to=businesses.models.company_logo_upload_path)),
                ('social_media_link', models.URLField(blank=True, max_length=512)),
                ('website', models.URLField(blank=True, max_length=512)),
                ('business_category', models.CharField(choices=[('retail', 'Retail'), ('f_b', 'Food & Beverage'), ('services', 'Services'), ('ecommerce', 'E-commerce'), ('manufacturing', 'Manufacturing'), ('tech', 'Technology'), ('creative', 'Creative / Media'), ('education', 'Education'), ('health', 'Health & Wellness'), ('other', 'Other')], max_length=32)),
                ('business_channel', models.JSONField(default=list, help_text='Multi-select: ecommerce, social_media, physical_store')),
                ('monthly_revenue_range', models.CharField(choices=[('under_1k', 'Under RM 1,000'), ('1k_5k', 'RM 1,000 - RM 5,000'), ('5k_10k', 'RM 5,000 - RM 10,000'), ('10k_25k', 'RM 10,000 - RM 25,000'), ('25k_50k', 'RM 25,000 - RM 50,000'), ('above_50k', 'Above RM 50,000')], max_length=32)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('consent_given', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('status_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Registration',
                'verbose_name_plural': 'Business Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
