# Generated by Django 4.2.27 on 2026-03-30 04:25

import businesses.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_pewakil_ssm_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, default='', max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='daerah',
            field=models.CharField(choices=[('johor_bahru', 'Johor Bahru'), ('muar', 'Muar'), ('batupahat', 'Batu Pahat'), ('kulaijaya', 'Kulai'), ('pontian', 'Pontian'), ('kluang', 'Kluang'), ('mersing', 'Mersing'), ('alor_setar', 'Alor Setar'), ('sungai_petani', 'Sungai Petani'), ('kulim', 'Kulim'), ('jitra', 'Jitra'), ('kota_bharu', 'Kota Bharu'), ('pasir_mas', 'Pasir Mas'), ('tanah_merah', 'Tanah Merah'), ('melaka_tengah', 'Melaka Tengah'), ('alor_gajah', 'Alor Gajah'), ('jasin', 'Jasin'), ('seremban', 'Seremban'), ('port_dickson', 'Port Dickson'), ('kuala_pilah', 'Kuala Pilah'), ('kuantan', 'Kuantan'), ('temerloh', 'Temerloh'), ('raub', 'Raub'), ('bentong', 'Bentong'), ('ipoh', 'Ipoh'), ('taiping', 'Taiping'), ('khota_setar', 'Kota Setar'), ('rawang', 'Rawang'), ('kangar', 'Kangar'), ('arau', 'Arau'), ('george_town', 'George Town'), ('seberang_perai', 'Seberang Perai'), ('kota_kinabalu', 'Kota Kinabalu'), ('sandakan', 'Sandakan'), ('tawau', 'Tawau'), ('kuching', 'Kuching'), ('miri', 'Miri'), ('sibu', 'Sibu'), ('petaling', 'Petaling'), ('klang', 'Klang'), ('shah_alam', 'Shah Alam'), ('subang_jaya', 'Subang Jaya'), ('kuala_terengganu', 'Kuala Terengganu'), ('kuantan', 'Kuantan'), ('kuala_lumpur', 'Kuala Lumpur'), ('labuan', 'Labuan'), ('putrajaya', 'Putrajaya'), ('other', 'Lain-lain')], max_length=64),
        ),
        migrations.AlterField(
            model_name='business',
            name='ssm_certificate',
            field=models.FileField(help_text='PDF or image upload', max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=businesses.models.ssm_certificate_upload_path),
        ),
    ]
